apiVersion: v1
kind: Namespace
metadata:
  name: asdasdsda-prod
  labels:
    environment-id: env_0d6d3a44-05c7-4686-aa8a-6737f9d98399
    project-id: project_ba59a3ac-0d33-4ad7-ba02-bd52b2fff3b1
    project-name: asdasdsda
    environment-name: prod
    organization-id: org_c50d7b26-1f2a-4a6e-b11e-469a86e002c8
