apiVersion: v1
kind: Namespace
metadata:
  name: dfgdfg-dev
  labels:
    environment-id: env_7e17d71f-4c1a-4aa5-b0cc-1a5d4556a016
    project-id: project_7e550c6e-7351-492c-ab84-ea089af75b85
    project-name: dfgdfg
    environment-name: dev
    organization-id: org_f20c804c-ee37-4760-be90-0335c55d7f42
